config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :fairies, only: [:new, :create]

  resources :fairies, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end

  resources :fairies, only: [:new, :create, :edit, :update, :destroy]


  resources :bookings, only: [:show] do
    collection do
      get :dashboard
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :fairy
end

app/models/fairy.rb
class Fairy < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_superpower_description,
    against: [
      [:name, 'A'],
      [:super_power, 'B'],
      [:description, 'C']
    ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fairies, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def dashboard
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @fairy = Fairy.find(params[:fairy_id])
  end

  def create
    @booking = Booking.new(booking_params)

    # then we need to set the booking's user_id and workspace_id
    @booking.user = current_user

    @fairy = Fairy.find(params[:fairy_id])
    @booking.fairy = @fairy

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/fairies_controller.rb
class FairiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  before_action :set_fairy, only: [ :show, :edit, :update ]
  def index
    if params[:search].present? && params[:search][:query].present?
      @fairies = Fairy.search_by_name_and_superpower_description(params[:search][:query])
    else
      @fairies = Fairy.all
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @fairy = Fairy.new
  end

  def create
    @fairy = Fairy.new(fairy_params)
    @fairy.user = current_user
    if @fairy.save
      # The notice will notify us the action has been performed
      redirect_to fairy_path(@fairy), notice: "Fairy has been created successfully"
    else
      render "new"
    end
  end


  def edit
  end

  def update
    if @fairy.update(fairy_params)
      redirect_to fairies_path
    else
      render :edit
    end
  end

  def destroy
    @fairy = Fairy.find(params[:id])
    @fairy.destroy
    redirect_to fairies_path

  end

  private

  def fairy_params
    params.require(:fairy).permit(:name, :super_power, :description, :price, :photo)
  end

  def set_fairy
    @fairy = Fairy.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @fairies = Fairy.first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/dashboard.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Booking history</h1>
    </div>
  </div>
  <div class="row d-block" >
    <% @bookings.each do |booking| %>
      <div class="col-md-4">
        <div class="card-product">
        <%= cl_image_tag booking.fairy.photo.key %>
          <div class="card-product-infos">
            <h2><%= booking.fairy.name %></h2>
            <p><strong> Price:</strong>€<%= booking.fairy.price %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Make a new booking for <%= @fairy.name %></h1>
<p> known for her <%=@fairy.super_power %>. <%= @fairy.description %> </p>

<%= simple_form_for [@fairy, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>

  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Congrats, you've made a booking!</h1>

<p>You are booking on <%= @booking.start_date %> and your magical fairy is: <%= @booking.fairy.name %>.</p>

app/views/fairies/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <h3>Edit Fairy</h3>
      <%= simple_form_for (@fairy) do |f| %>
        <%= f.input :name %>
        <%= f.input :super_power %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
        <%= link_to 'Back', fairies_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/fairies/index.html.erb
<!-- GIVE SPACING OR PADDING HERE TO MAKE NAV BAR VISIBLE -->

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Fairies</h1>
    </div>
  </div>

  <div class="row">
    <% @fairies.each do |fairy| %>
      <div class="col-md-4">
        <div class="fairy-card">
          <%= cl_image_tag fairy.photo.key, height: 300, width: 400, crop: :fill %>
          <div class="fairy-card-content">
            <div class="fairy-card-title">
              <h4><%= fairy.name %></h4>
            </div>
            <p><%= fairy.description %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons me-2">🧚🏼</i><span>€<%= fairy.price %></span>
              </div>
              <div class="flex ms-3">
                <i class="material-icons me-2"><strong>Power:</strong> <%= fairy.super_power %></i>
              </div>
            </div>
          </div>
          <div class="fairy-card-actions">
            <%= link_to "VIEW", fairy_path(fairy) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/fairies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <h3>Edit Fairy</h3>
      <%= simple_form_for (@fairy) do |f| %>
        <%= f.input :name %>
        <%= f.input :super_power %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
        <%= link_to 'Back', fairies_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/fairies/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ti-icons@0.1.2/css/themify-icons.css">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7 col-lg-4 mb-5 mb-lg-0 wow fadeIn">
            <div class="card border-0 shadow">
                <%= cl_image_tag @fairy.photo.key, height: 300, width: 400, crop: :fill %>
                <div class="card-body p-1-9 p-xl-5">
                    <div class="mb-4">
                        <h3 class="h4 mb-0"><%= @fairy.name %></h3>
                        <span class="text-powers"><strong>SUPERPOWER:</strong> <%= @fairy.super_power %> </span>
                        <span class="text-powers"><strong>PRICE:</strong> €<%= @fairy.price %> </span>
                    </div>
                    <ul class="list-unstyled mb-4">
                        <%= simple_form_for [@fairy, @booking] do |f| %>
                          <%= f.input :start_date %>
                          <%= f.input :end_date %>
                          <%= f.submit %>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="ps-lg-1-6 ps-xl-5">
                <div class="mb-5 wow fadeIn">
                    <div class="text-start mb-1-6 wow fadeIn">
                        <h2 class="h1 mb-0 text-primary">About <%= @fairy.name %></h2>
                    </div>
                    <p class="mb-0"><%= @fairy.description %></p>
                </div>
                <div class="mb-5 wow fadeIn">
                    <div class="text-start mb-1-6 wow fadeIn">
                        <h2 class="mb-0 text-primary">Powers</h2>
                    </div>
                    <div class="row mt-n4">
                        <div class="col-sm-6 col-xl-4 mt-4">
                            <div class="card text-center border-0 rounded-3">
                                <div class="card-body">
                                    <i class="ti-bookmark-alt icon-box medium rounded-3 mb-4"></i>
                                    <h3 class="h5 mb-3">Coding</h3>
                                    <p class="mb-0">Keeps you coding when you're feeling down</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xl-4 mt-4">
                            <div class="card text-center border-0 rounded-3">
                                <div class="card-body">
                                    <i class="ti-pencil-alt icon-box medium rounded-3 mb-4"></i>
                                    <h3 class="h5 mb-3">Documentation</h3>
                                    <p class="mb-0">Reads all the documentation for you so you don't ever have to!</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-xl-4 mt-4">
                            <div class="card text-center border-0 rounded-3">
                                <div class="card-body">
                                    <i class="ti-medall-alt icon-box medium rounded-3 mb-4"></i>
                                    <h3 class="h5 mb-3">Languages</h3>
                                    <p class="mb-0">Knows every programming language's methods and functions by heart</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<%# <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Daily Fairies <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyFairyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "black"%>
          </li>
          <li class="nav-item">
            <%= link_to "View Fairies", fairies_path, class: "black" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_bookings_path, class: "black" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Fairy", new_fairy_path, class: "black" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Sign in", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>
    <%= yield %>
    <%# <%= render "./layouts/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('fairy_home_banner.jpg') %>);">
  <div class="container">
    <h1>DAILY FAIRIES</h1>
    <h2><strong>Magical creatures</strong> for <strong>cheap people</strong>!</h2>
    <p>Change your life with magic by renting one of our fairies from around the universe.</p>
    <%= link_to "VIEW FAIRIES 🧚🏼", fairies_path, class:  "btn btn-flat", id: "view_fairies"  %>
  </div>
</div>

<%= simple_form_for :search, url: fairies_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Tell us your wish..." />
    <button name="button" type="submit" class="btn btn-flat" id="search_bar">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

<h2 class="world-class-fairies"><strong>Find your muse</strong></h2>
<div class="cards">
  <% @fairies.each do |fairy|  %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path fairy.photo.key %>)">
       <div class="fairy-card-actions">

            <%= link_to fairy.name, fairy_path(fairy) %>

          </div>
      <%# cloudinary_url("sample.jpg", :resource_type => :raw)  %>
      <%# <%= cl_image_tag fairy.photo.key, height: 300, width: 400, crop: :fill %>
    </div>
  <% end  %>
</div>




<div class="container">
    <%= link_to "VIEW AVAILABLE FAIRIES 🧚🏼", fairies_path, class:  "btn btn-flat", id: "avail_fairies"  %>
</div>